// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'jsdom',
    setupFiles: ['<rootDir>/jest.config.js', 'jest-canvas-mock'],
    coveragePathIgnorePatterns: ['jest.config.js','src/Training/App.css','src/Training/View.tsx','src/Training/strategies/Regression/AlgorithmViewRegression.tsx','src/Training/strategies/SVM/AlgorithmViewSVM.tsx','src/test/*','src/appView.tsx','src/module.ts','src/panels/PredictionPanel/module.ts','src/panels/PredictionPanel/PanelView.tsx','src/panels/PredictionPanel/EditorView.tsx'],
    moduleNameMapper: {
        "^.+\\.(css|less|scss)$": "identity-obj-proxy"
    },
    resolver: null
};
